server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_security?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      timeout: 2000
      database: 5
      port: 6379
      jedis:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 10
          min-idle: 0
  jackson:
    default-property-inclusion: non_null
    date-format: YYYY-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  type-aliases-package: com.ruoyisecurity.domain
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.ruoyisecurity: debug
  pattern:
    dateformat: HH:mm:ss

security:
  whiteList:
    - "/login"
    - "/logout"
    - "/captcha"
    - "/image/**"

jwt:
  expire-time: 120
  secret: "khr"

uploadImagePath: "D:/ruoYi/uploadPath"