server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-config-slice-X.yml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false