# shardingsphere读写分离配置
dataSources:
  master:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.31.247.73:3307/db_user
    username: root
    password: 123456
  slave1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.31.247.73:3308/db_user
    username: root
    password: 123456
  slave2:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.31.247.73:3309/db_user
    username: root
    password: 123456
rules:
  - !READWRITE_SPLITTING
    dataSources:
      # 读写分离逻辑数据源名称
      readwrite_ds:
        # 读写分离类型
        staticStrategy:
          # 写库数据源名称
          writeDataSourceName: master
          # 读库数据源名称，多个从数据源用逗号分隔，或者使用数组表示
          readDataSourceNames:
            - slave1
            - slave2
        # 负载均衡算法名称
        loadBalancerName: alg_weight
    # 负载均衡算法配置
    loadBalancers:
      alg_roundRobin:
        type: ROUND_ROBIN
      alg_random:
        type: RANDOM
      alg_weight:
        props:
          slave1: 1.0
          slave2: 2.0
        type: WEIGHT

props:
  sql-show: true
